### ISSUE TITLE
PTPX makes an anti-requirement which uses the wrong variable from the cst

### ISSUE THREAD

**Issue by jefft0** [IIIM-IS/AERA#245]
In hand-grab-sphere-learn, AERA learns a grab model `mdl_252` which is used both to grab a cube or a sphere (simplified):

    mdl_252:(mdl [v0: v1: v2:] []
       (fact (cmd grab [v3:] :) v4: v5:)
       (fact (mk.val v3: holding [v6:]) v7: v8:))

In the example, AERA releases the cube `c` in the same position as the sphere `s`, then issues the grab command. Correctly (with the information available), AERA uses this model twice to predict both `(mk.val h holding [c])` and `(mk.val h holding [s])` . When grab fails, PTPX is invoked to learn the anti-requirement to explain the conditions under which model `mdl_252` will fail. When the prediction to grab a sphere is the failure, PTPX makes the following (simplified and variables names clarified):

    cst_1439:(cst [] []
       (fact (icst cst_441 [] [Hand: Cube: P:] : :) T0: T1:)
       (fact (icst cst_251 [] [Hand: Sphere: P:] : :) T0: T1:))
    mdl_1440:(mdl [] []
       (fact (icst cst_1439 [] [Hand: Cube: P: Sphere:]) T0: T1:)
       (|fact (imdl mdl_252 [[] T0: T1:] [Hand: Sphere: v7: v8:]) T0: T1:))

This says that if `cst_441` (hand at position of cube) and `cst_251` (hand at position of sphere) are both instantiated, then the grab model `mdl_252` will fail. Technically it says that grabbing a sphere will fail because in `icst cst_1439` variable `Sphere` is the sphere. When this is used to make `imdl mdl_252`, it is the argument which is bound to `v6` in `mdl_252` which is used in `(mk.val v3: holding [v6:])`.

PTPX is also invoked to explain the failed prediction of grabbing the cube. It makes `cst_1442` and `mdl_1443` which are identical to `cst_1439` and `mdl_1440`. These should be for predicting when `mdl_252` will fail to grab a cube. The problem is: since they are identical, `imdl mdl_252` still uses the `Sphere` variable from `icst cst_1439`, not the cube. PTPX should use the `Cube` variable from `icst cst_1439`.

**Comment by thorisson** [comment]
Are we sure it is "wrong"? In every case that something along these lines happens, can we be sure that what it does now will not be useful in some way? Another way of questioning this is: are we sure AERA *can* know which variable to use? Is it possible it might be better to do what it currently does AND the alternative - i.e. use the other variable?=KOn 1 Feb 2023, at 16:38, Jeff Thompson ***@***.***> wrote:﻿
In hand-grab-sphere-learn, AERA learns a grab model mdl_252 which is used both to grab a cube or a sphere (simplified):
mdl_252:(mdl [v0: v1: v2:] []
   (fact (cmd grab [v3:] :) v4: v5:)
   (fact (mk.val v3: holding [v6:]) v7: v8:))

In the example, AERA releases the cube c in the same position as the sphere s, then issues the grab command. Correctly (with the information available), AERA uses this model twice to predict both (mk.val h holding [c]) and (mk.val h holding [s]) . When grab fails, PTPX is invoked to learn the anti-requirement to explain the conditions under which model mdl_252 will fail. When the prediction to grab a sphere is the failure, PTPX makes the following (simplified):
cst_1439:(cst [] []
   (fact (icst cst_441 [] [v0: v3: v4:] : :) v1: v2:)
   (fact (icst cst_251 [] [v0: v5: v4:] : :) v1: v2:))
mdl_1440:(mdl [] []
   (fact (icst cst_1439 [] [v0: v1: v2: v3:]) v4: v5:)
   (|fact (imdl mdl_252 [[] v4: v5:] [v0: v3: v6: v7:]) v4: v5:))

This says that if cst_441 (hand at position of cube) and cst_251 (hand at position of sphere) are both instantiated, then the grab model mdl_252 will fail. Technically it says that grabbing a sphere will fail because in icst cst_1439 variable v3 is the sphere. When this is used to make imdl mdl_252, it is the argument which is bound to v6 in mdl_252 which is used in (mk.val v3: holding [v6:]).
PTPX is also invoked to explain the failed prediction of grabbing the cube. It makes cst_1442 and mdl_1443 which are identical to cst_1439 and mdl_1440. These should be for predicting when mdl_252 will fail to grab a cube. The problem is: since they are identical, imdl mdl_252 still uses v3 from icst cst_1439 which is the sphere, not the cube. PTPX should use v1 from icst cst_1439 which is the cube.

**Comment by jefft0** [comment]
Closed as resolved by pull request #246.
